# Uncomment this line to define a global platform for your project
platform :ios, "7.0" #コメントを外して :ios, '7.0'にすることを忘れずに

target "iPhone2Rails" do
pod 'AFNetworking', '~>2.4.1' #追加
end

target "iPhone2RailsTests" do

end

